### ISSUE TITLE
Additional related

### ISSUE THREAD

**Issue by KnowledgeGarden** [FactGraph/FactGraph#2]
Feel free to delete this issue:

(same people who brought Compendium to open source)
http://evidence-hub.net/
http://cohere.open.ac.uk/ which has been retired (very powerful, but complex UX) points to
https://litemap.net/
The temporal sequence is Cohere, then Compendium (donated to the University), then Evidence-Hub, ending with LiteMap;
Observe that the migration is from truly complex UX, to the simplicity of a pro-con debate.

**Comment by fdietze** [comment]
I added them to the list! :+1:
